apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marginalia-data
  namespace: marginalia
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
